# Generated by Django 5.1.3 on 2024-11-11 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_prelaunchemail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PreLaunchEmail',
            new_name='WaitlistEmail',
        ),
    ]
