# Generated by Django 5.1.3 on 2024-11-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_prelaunchemail_waitlistemail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waitlistemail',
            name='id',
        ),
        migrations.AddField(
            model_name='waitlistemail',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='waitlistemail',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
