# Generated by Django 5.1.3 on 2024-11-11 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_waitlistemail_id_waitlistemail_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waitlistemail',
            old_name='date',
            new_name='date_enrolled',
        ),
    ]
