# Generated by Django 5.1.3 on 2025-01-07 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_plaidcashbacktransaction_robinhoodcashbackdeposit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbrokerageinfo',
            name='password',
        ),
        migrations.RemoveField(
            model_name='userbrokerageinfo',
            name='username',
        ),
    ]
