# Generated by Django 5.1.3 on 2025-01-15 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_userplaidinfo_accesstoken_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplaidinfo',
            name='countryCodes',
            field=models.CharField(choices=[], default=None, max_length=2, null=True),
        ),
    ]
