# Generated by Django 5.2.1 on 2025-05-26 07:38

import api.serializers.plaid.link
import django.contrib.auth.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAnonInvestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField()),
                ('symbol', models.CharField(default=None, max_length=255, null=True)),
                ('date', models.DateField()),
                ('quantity', models.FloatField()),
                ('buy', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='LogAnonPlaid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField()),
                ('items', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('VOO', models.FloatField(default=None, null=True)),
                ('VOOG', models.FloatField(default=None, null=True)),
                ('QQQ', models.FloatField(default=None, null=True)),
                ('IBIT', models.FloatField(default=None, null=True)),
                ('date', models.DateTimeField(primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='WaitlistEmail',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('date_enrolled', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('phone_number', models.CharField(max_length=15, unique=True, validators=[api.serializers.plaid.link.e164_phone_number_validator])),
                ('full_name', models.TextField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='LogAnon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('method', models.CharField()),
                ('user', models.CharField(default=None, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('errors', models.JSONField(default=None, null=True)),
                ('state', models.CharField()),
                ('status', models.IntegerField()),
                ('pre_account_id', models.CharField(default=None, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['date', 'status', 'state'], name='api_loganon_date_4626fb_idx'), models.Index(fields=['user', 'date', 'status', 'state'], name='api_loganon_user_c5b061_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlaidLinkWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(null=True)),
                ('link_session_id', models.CharField()),
                ('link_token', models.CharField()),
                ('request_id', models.CharField(null=True)),
                ('institution_name', models.CharField(null=True)),
                ('view_name', models.CharField(null=True)),
                ('webhook_code', models.CharField()),
                ('exit_status', models.CharField(null=True)),
                ('error_code', models.CharField(null=True)),
                ('error_message', models.CharField(null=True)),
                ('error_type', models.CharField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlaidPersonalFinanceCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dining', models.FloatField(default=0)),
                ('groceries', models.FloatField(default=0)),
                ('utilities', models.FloatField(default=0)),
                ('travel', models.FloatField(default=0)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlaidUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countryCodes', models.CharField(choices=[], default=None, max_length=2, null=True)),
                ('language', models.CharField(choices=[], default=None, max_length=2, null=True)),
                ('_userToken', models.BinaryField()),
                ('userTokenDek', models.BinaryField()),
                ('userId', models.CharField(max_length=255)),
                ('clientUserId', models.CharField(max_length=255)),
                ('link_token', models.CharField(default=None, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RobinhoodDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_id', models.CharField(max_length=255)),
                ('rh_account_id', models.CharField(max_length=255)),
                ('rh_account_ach', models.CharField(max_length=255)),
                ('plaid_account_id', models.CharField(max_length=255, null=True)),
                ('mask', models.CharField(max_length=4)),
                ('state', models.CharField(max_length=255)),
                ('early_access_amount', models.FloatField(null=True)),
                ('amount', models.FloatField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('expected_landing_datetime', models.DateTimeField()),
                ('cancel', models.CharField(max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('mask', models.CharField(max_length=4)),
                ('state', models.CharField(max_length=255)),
                ('early_access_amount', models.FloatField(null=True)),
                ('amount', models.FloatField()),
                ('created_at', models.DateTimeField()),
                ('flag', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rh', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.robinhooddeposit')),
            ],
        ),
        migrations.CreateModel(
            name='RobinhoodStockOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=255)),
                ('cancel', models.CharField(max_length=255, null=True)),
                ('instrument_id', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=255, null=True)),
                ('state', models.CharField(max_length=255)),
                ('side', models.CharField(max_length=255)),
                ('quantity', models.FloatField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('pending_cancel_open_agent', models.CharField(max_length=255, null=True)),
                ('requested_amount', models.FloatField()),
                ('executed_amount', models.FloatField(null=True)),
                ('user_cancel_request_state', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user', 'updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(default=None, max_length=255, null=True)),
                ('quantity', models.FloatField()),
                ('cumulative_quantities', models.JSONField(default=dict)),
                ('date', models.DateTimeField()),
                ('buy', models.BooleanField()),
                ('deposit', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.deposit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rh', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.robinhoodstockorder')),
            ],
            options={
                'ordering': ['user', 'date'],
            },
        ),
        migrations.CreateModel(
            name='UserBrokerageInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brokerage', models.CharField(default=None, max_length=255, null=True)),
                ('symbol', models.CharField(default=None, max_length=255, null=True)),
                ('overdraft_protection', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserInvestmentGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('value', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('method', models.CharField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('errors', models.JSONField(default=None, null=True)),
                ('state', models.CharField()),
                ('status', models.IntegerField()),
                ('pre_account_id', models.PositiveIntegerField(default=None, null=True)),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['date', 'status', 'state'], name='api_log_date_9bd879_idx'), models.Index(fields=['user', 'date', 'status', 'state'], name='api_log_user_id_f8f1c8_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlaidCashbackTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=255)),
                ('transaction_id', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('pending', models.BooleanField()),
                ('iso_currency_code', models.CharField(max_length=10)),
                ('date', models.DateField(default=None, null=True)),
                ('authorized_date', models.DateField(default=None, null=True)),
                ('authorized_datetime', models.DateTimeField(default=None, null=True)),
                ('name', models.CharField()),
                ('flag', models.BooleanField(default=False)),
                ('deposit', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.deposit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'transaction_id'), name='unique_plaid_transaction')],
            },
        ),
        migrations.CreateModel(
            name='PlaidItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('itemId', models.CharField(max_length=255, unique=True)),
                ('_accessToken', models.BinaryField()),
                ('accessTokenDek', models.BinaryField()),
                ('previousRefresh', models.DateTimeField(auto_now=True)),
                ('transactionsCursor', models.CharField(default=None, max_length=255, null=True)),
                ('update_code', models.CharField(default=None, max_length=255, null=True)),
                ('institution_name', models.CharField(default=None, max_length=255, null=True)),
                ('institution_id', models.CharField(default=None, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'itemId'), name='unique_plaid_item')],
            },
        ),
        migrations.AddConstraint(
            model_name='robinhooddeposit',
            constraint=models.UniqueConstraint(fields=('user', 'deposit_id'), name='unique_rh_deposit'),
        ),
        migrations.AddIndex(
            model_name='robinhoodstockorder',
            index=models.Index(fields=['order_id'], name='api_robinho_order_i_2ae2e7_idx'),
        ),
        migrations.AddIndex(
            model_name='robinhoodstockorder',
            index=models.Index(fields=['user', 'updated_at'], name='api_robinho_user_id_77b921_idx'),
        ),
        migrations.AddConstraint(
            model_name='robinhoodstockorder',
            constraint=models.UniqueConstraint(fields=('user', 'order_id'), name='unique_rh_order'),
        ),
        migrations.AddIndex(
            model_name='investment',
            index=models.Index(fields=['user', 'date'], name='api_investm_user_id_0318fa_idx'),
        ),
        migrations.AddIndex(
            model_name='userinvestmentgraph',
            index=models.Index(fields=['date'], name='api_userinv_date_67a1b1_idx'),
        ),
        migrations.AddIndex(
            model_name='userinvestmentgraph',
            index=models.Index(fields=['user', 'date'], name='api_userinv_user_id_c47680_idx'),
        ),
        migrations.AddConstraint(
            model_name='userinvestmentgraph',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='user_portfolio_value_by_date'),
        ),
    ]
