# Generated by Django 5.2.1 on 2025-05-21 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='investment',
            name='unique_investment',
        ),
        migrations.RemoveField(
            model_name='plaiditem',
            name='plaid_item',
        ),
        migrations.RemoveField(
            model_name='plaiditem',
            name='previousRefreshSuccess',
        ),
        migrations.RemoveField(
            model_name='plaidpersonalfinancecategories',
            name='entertainment',
        ),
        migrations.RemoveField(
            model_name='plaidpersonalfinancecategories',
            name='food_and_drink',
        ),
        migrations.RemoveField(
            model_name='plaidpersonalfinancecategories',
            name='general_merchandise',
        ),
        migrations.RemoveField(
            model_name='plaidpersonalfinancecategories',
            name='home_improvement',
        ),
        migrations.RemoveField(
            model_name='plaidpersonalfinancecategories',
            name='personal_care',
        ),
        migrations.RemoveField(
            model_name='plaidpersonalfinancecategories',
            name='rent_and_utilities',
        ),
        migrations.RemoveField(
            model_name='plaidpersonalfinancecategories',
            name='transportation',
        ),
        migrations.AddField(
            model_name='plaidpersonalfinancecategories',
            name='dining',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='plaidpersonalfinancecategories',
            name='groceries',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='plaidpersonalfinancecategories',
            name='utilities',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='early_access_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='robinhooddeposit',
            name='early_access_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='robinhooddeposit',
            name='plaid_account_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
