# Generated by Django 5.2.1 on 2025-05-26 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plaidlinkwebhook',
            name='link_session_id',
            field=models.CharField(null=True),
        ),
    ]
