# Generated by Django 5.1.3 on 2025-03-09 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbrokerageinfo',
            name='brokerage',
            field=models.CharField(choices=[('robinhood', 'robinhood')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userbrokerageinfo',
            name='symbol',
            field=models.CharField(choices=[('VOO', 'VOO'), ('VOOG', 'VOOG'), ('QQQ', 'QQQ'), ('IBIT', 'IBIT')], default=None, max_length=255, null=True),
        ),
    ]
