# Generated by Django 5.1.3 on 2025-03-25 11:31

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='robinhoodstockorder',
            options={'ordering': ['updated_at', 'symbol']},
        ),
        migrations.AlterModelOptions(
            name='stockdata',
            options={'ordering': ['date']},
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='cursor',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='dailyPrice',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='id',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='startDate',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='symbol',
        ),
        migrations.AddField(
            model_name='robinhoodstockorder',
            name='symbol',
            field=models.CharField(choices=[('VOO', 'VOO'), ('VOOG', 'VOOG'), ('QQQ', 'QQQ'), ('IBIT', 'IBIT')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='IBIT',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='QQQ',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='VOO',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='VOOG',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 25, 11, 31, 37, 576502, tzinfo=datetime.timezone.utc), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userbrokerageinfo',
            name='brokerage',
            field=models.CharField(choices=[('robinhood', 'robinhood'), ('webull', 'webull'), ('charles_schwab', 'charles_schwab'), ('fidelity', 'fidelity')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userbrokerageinfo',
            name='symbol',
            field=models.CharField(choices=[('VOO', 'VOO'), ('VOOG', 'VOOG'), ('QQQ', 'QQQ'), ('IBIT', 'IBIT')], default=None, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Investments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_id', models.CharField(max_length=255)),
                ('symbol', models.CharField(choices=[('VOO', 'VOO'), ('VOOG', 'VOOG'), ('QQQ', 'QQQ'), ('IBIT', 'IBIT')], default=None, max_length=255, null=True)),
                ('brokerage', models.CharField(choices=[('robinhood', 'robinhood'), ('webull', 'webull'), ('charles_schwab', 'charles_schwab'), ('fidelity', 'fidelity')], default=None, max_length=255, null=True)),
                ('quantity', models.FloatField()),
                ('cumulative_quantities', models.JSONField(default=dict)),
                ('date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserInvestmentGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2025, 3, 25, 11, 31, 37, 575222, tzinfo=datetime.timezone.utc))),
                ('value', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['date'], name='api_userinv_date_67a1b1_idx'), models.Index(fields=['user', 'date'], name='api_userinv_user_id_c47680_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='user_portfolio_value_by_date')],
            },
        ),
    ]
