# Generated by Django 5.1.3 on 2025-04-22 11:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('mask', models.CharField(max_length=4)),
                ('state', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('created_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(default=None, max_length=255, null=True)),
                ('quantity', models.FloatField()),
                ('cumulative_quantities', models.JSONField(default=dict)),
                ('date', models.DateTimeField()),
                ('buy', models.BooleanField()),
            ],
            options={
                'ordering': ['user', 'date'],
            },
        ),
        migrations.CreateModel(
            name='LogAnonInvestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField()),
                ('symbol', models.CharField(default=None, max_length=255, null=True)),
                ('date', models.DateField()),
                ('quantity', models.FloatField()),
                ('buy', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PlaidPersonalFinanceCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_in', models.FloatField(default=0)),
                ('transfer_out', models.FloatField(default=0)),
                ('loan_payments', models.FloatField(default=0)),
                ('bank_fees', models.FloatField(default=0)),
                ('entertainment', models.FloatField(default=0)),
                ('food_and_drink', models.FloatField(default=0)),
                ('general_merchandise', models.FloatField(default=0)),
                ('home_improvement', models.FloatField(default=0)),
                ('medical', models.FloatField(default=0)),
                ('personal_care', models.FloatField(default=0)),
                ('general_services', models.FloatField(default=0)),
                ('government_and_non_profit', models.FloatField(default=0)),
                ('transportation', models.FloatField(default=0)),
                ('travel', models.FloatField(default=0)),
                ('rent_and_utilities', models.FloatField(default=0)),
                ('income', models.FloatField(default=0)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RobinhoodDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_id', models.CharField(max_length=255)),
                ('rh_account_id', models.CharField(max_length=255)),
                ('rh_account_ach', models.CharField(max_length=255)),
                ('plaid_account_id', models.CharField(max_length=255)),
                ('mask', models.CharField(max_length=4)),
                ('state', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('expected_landing_datetime', models.DateTimeField()),
                ('cancel', models.CharField(max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='investments',
            name='deposit',
        ),
        migrations.RemoveField(
            model_name='investments',
            name='user',
        ),
        migrations.DeleteModel(
            name='LogAnonInvestments',
        ),
        migrations.RemoveField(
            model_name='robinhoodcashbackdeposit',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='robinhoodcashbackdeposit',
            name='user',
        ),
        migrations.RemoveField(
            model_name='robinhoodstockorder',
            name='deposit',
        ),
        migrations.RemoveField(
            model_name='plaidcashbacktransaction',
            name='deposited',
        ),
        migrations.AddField(
            model_name='plaidcashbacktransaction',
            name='authorized_datetime',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='plaidcashbacktransaction',
            name='date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='plaidcashbacktransaction',
            name='iso_currency_code',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='plaidcashbacktransaction',
            name='name',
            field=models.CharField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='plaidcashbacktransaction',
            name='pending',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='plaidcashbacktransaction',
            name='authorized_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='robinhoodstockorder',
            name='symbol',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userbrokerageinfo',
            name='brokerage',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userbrokerageinfo',
            name='symbol',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='plaidcashbacktransaction',
            name='deposit',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.deposit'),
        ),
        migrations.AddField(
            model_name='investment',
            name='rh',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.robinhoodstockorder'),
        ),
        migrations.AddField(
            model_name='investment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deposit',
            name='investment',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.investment'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='rh',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.robinhooddeposit'),
        ),
        migrations.DeleteModel(
            name='Investments',
        ),
        migrations.DeleteModel(
            name='RobinhoodCashbackDeposit',
        ),
        migrations.AddIndex(
            model_name='investment',
            index=models.Index(fields=['user', 'date'], name='api_investm_user_id_0318fa_idx'),
        ),
        migrations.AddConstraint(
            model_name='investment',
            constraint=models.UniqueConstraint(fields=('user', 'buy'), name='unique_investment'),
        ),
        migrations.AddConstraint(
            model_name='robinhooddeposit',
            constraint=models.UniqueConstraint(fields=('user', 'deposit_id'), name='unique_rh_deposit'),
        ),
    ]

