# Generated by Django 5.2.1 on 2025-05-26 09:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_plaidlinkwebhook_link_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='plaidlinkwebhook',
            name='time_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='log',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='loganon',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='waitlistemail',
            name='date_enrolled',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
