# Generated by Django 5.1.3 on 2025-03-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_userbrokerageinfo_brokerage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbrokerageinfo',
            name='brokerage',
            field=models.CharField(choices=[('robinhood', 'robinhood'), ('webull', 'webull'), ('charles_schwab', 'charles_schwab'), ('fidelity', 'fidelity')], default=None, max_length=255, null=True),
        ),
    ]
