# Generated by Django 5.1.3 on 2025-03-25 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_robinhoodstockorder_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdata',
            name='date',
            field=models.DateTimeField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userinvestmentgraph',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='userinvestmentgraph',
            name='value',
            field=models.FloatField(),
        ),
    ]
