# Generated by Django 5.1.3 on 2025-03-19 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_userbrokerageinfo_brokerage'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockDataByDay',
            fields=[
                ('VOO', models.FloatField(default=None)),
                ('VOOG', models.FloatField(default=None)),
                ('QQQ', models.FloatField(default=None)),
                ('IBIT', models.FloatField(default=None)),
                ('date', models.DateTimeField(primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='StockDataByHour',
            fields=[
                ('VOO', models.FloatField(default=None)),
                ('VOOG', models.FloatField(default=None)),
                ('QQQ', models.FloatField(default=None)),
                ('IBIT', models.FloatField(default=None)),
                ('date', models.DateTimeField(primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='StockDataByMinute',
            fields=[
                ('VOO', models.FloatField(default=None)),
                ('VOOG', models.FloatField(default=None)),
                ('QQQ', models.FloatField(default=None)),
                ('IBIT', models.FloatField(default=None)),
                ('date', models.DateTimeField(primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='StockDataByMonth',
            fields=[
                ('VOO', models.FloatField(default=None)),
                ('VOOG', models.FloatField(default=None)),
                ('QQQ', models.FloatField(default=None)),
                ('IBIT', models.FloatField(default=None)),
                ('date', models.DateTimeField(primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.DeleteModel(
            name='StockData',
        ),
        migrations.AlterModelOptions(
            name='robinhoodstockorder',
            options={'ordering': ['updated_at', 'symbol']},
        ),
        migrations.AddField(
            model_name='robinhoodstockorder',
            name='symbol',
            field=models.CharField(choices=[('VOO', 'VOO'), ('VOOG', 'VOOG'), ('QQQ', 'QQQ'), ('IBIT', 'IBIT')], max_length=255, null=True),
        ),
    ]
