# Generated by Django 5.2.1 on 2025-05-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_plaidlinkwebhook_time_created_alter_log_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plaidlinkwebhook',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
