# Generated by Django 5.1.3 on 2025-04-22 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_plaidcashbacktransaction_iso_currency_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plaidcashbacktransaction',
            name='iso_currency_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='plaidcashbacktransaction',
            name='name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='plaidcashbacktransaction',
            name='pending',
            field=models.BooleanField(),
        ),
    ]


