# Generated by Django 5.1.3 on 2025-03-25 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_stockdata_date_alter_userinvestmentgraph_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitlistemail',
            name='date_enrolled',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
