# Generated by Django 5.1.3 on 2025-03-19 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_stockdatabyday_stockdatabyhour_stockdatabyminute_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdatabyday',
            name='IBIT',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='stockdatabyday',
            name='QQQ',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='stockdatabyday',
            name='VOO',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='stockdatabyday',
            name='VOOG',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='stockdatabyhour',
            name='IBIT',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='stockdatabyhour',
            name='QQQ',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='stockdatabyhour',
            name='VOO',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='stockdatabyhour',
            name='VOOG',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='stockdatabyminute',
            name='IBIT',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='stockdatabyminute',
            name='QQQ',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='stockdatabyminute',
            name='VOO',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='stockdatabyminute',
            name='VOOG',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='stockdatabymonth',
            name='IBIT',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='stockdatabymonth',
            name='QQQ',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='stockdatabymonth',
            name='VOO',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='stockdatabymonth',
            name='VOOG',
            field=models.FloatField(default=None, null=True),
        ),
    ]
