# Generated by Django 5.1.3 on 2025-04-22 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_plaidcashbacktransaction_iso_currency_code_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='investment',
            name='unique_investment',
        ),
        migrations.AddConstraint(
            model_name='investment',
            constraint=models.UniqueConstraint(fields=('user', 'date', 'buy'), name='unique_investment'),
        ),
    ]
