# Generated by Django 5.2.1 on 2025-06-17 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_plaidlinkwebhook_time_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='app_version',
            field=models.CharField(default='pre_build_8'),
        ),
    ]
