# Generated by Django 5.1.3 on 2025-03-28 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_waitlistemail_date_enrolled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('user', models.DateTimeField(default=None, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('args', models.JSONField()),
                ('response', models.JSONField()),
                ('status', models.IntegerField()),
                ('success', models.BooleanField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='investments',
            options={'ordering': ['user', 'date']},
        ),
        migrations.AlterModelOptions(
            name='robinhoodstockorder',
            options={'ordering': ['user', 'updated_at']},
        ),
        migrations.AddField(
            model_name='investments',
            name='buy',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='investments',
            name='deposit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.robinhoodcashbackdeposit'),
        ),
        migrations.AddIndex(
            model_name='investments',
            index=models.Index(fields=['investment_id'], name='api_investm_investm_195a44_idx'),
        ),
        migrations.AddIndex(
            model_name='investments',
            index=models.Index(fields=['user', 'date'], name='api_investm_user_id_8cbb82_idx'),
        ),
        migrations.AddIndex(
            model_name='robinhoodstockorder',
            index=models.Index(fields=['order_id'], name='api_robinho_order_i_2ae2e7_idx'),
        ),
        migrations.AddIndex(
            model_name='robinhoodstockorder',
            index=models.Index(fields=['user', 'updated_at'], name='api_robinho_user_id_77b921_idx'),
        ),
        migrations.AddConstraint(
            model_name='investments',
            constraint=models.UniqueConstraint(fields=('user', 'investment_id', 'brokerage', 'buy'), name='unique_investment'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['date', 'success', 'status'], name='api_log_date_d26d31_idx'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['user', 'date', 'success', 'status'], name='api_log_user_ee5988_idx'),
        ),
    ]
