# Generated by Django 5.2.1 on 2025-06-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_app_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='plaidlinkwebhook',
            name='event_id',
            field=models.UUIDField(null=True),
        ),
        migrations.AddIndex(
            model_name='plaidlinkwebhook',
            index=models.Index(fields=['user', 'link_session_id', 'event_id'], name='api_plaidli_user_id_c5a57a_idx'),
        ),
        migrations.AddConstraint(
            model_name='plaidlinkwebhook',
            constraint=models.UniqueConstraint(fields=('user', 'link_session_id', 'event_id'), name='plaidevent'),
        ),
    ]
