# Generated by Django 5.1.3 on 2025-03-22 00:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_stockdatabyday_ibit_alter_stockdatabyday_qqq_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_id', models.CharField(max_length=255)),
                ('symbol', models.CharField(choices=[('VOO', 'VOO'), ('VOOG', 'VOOG'), ('QQQ', 'QQQ'), ('IBIT', 'IBIT')], default=None, max_length=255, null=True)),
                ('brokerage', models.CharField(choices=[('robinhood', 'robinhood'), ('webull', 'webull'), ('charles_schwab', 'charles_schwab'), ('fidelity', 'fidelity')], default=None, max_length=255, null=True)),
                ('quantity', models.FloatField()),
                ('cumulative_quantities', models.JSONField(default={})),
                ('date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('VOO', models.FloatField(default=None, null=True)),
                ('VOOG', models.FloatField(default=None, null=True)),
                ('QQQ', models.FloatField(default=None, null=True)),
                ('IBIT', models.FloatField(default=None, null=True)),
                ('date', models.DateTimeField(primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='UserInvestmentGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=[])),
                ('most_recent_date', models.DateField()),
                ('cumulative_amount', models.JSONField(default={})),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='StockDataByDay',
        ),
        migrations.DeleteModel(
            name='StockDataByHour',
        ),
        migrations.DeleteModel(
            name='StockDataByMinute',
        ),
        migrations.DeleteModel(
            name='StockDataByMonth',
        ),
    ]
