# Generated by Django 5.1.3 on 2025-03-28 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_log_alter_investments_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investments',
            name='buy',
            field=models.BooleanField(),
        ),
    ]
