# Generated by Django 5.1.3 on 2025-05-08 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_investment_unique_investment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='investment',
        ),
        migrations.RemoveField(
            model_name='plaidpersonalfinancecategories',
            name='bank_fees',
        ),
        migrations.RemoveField(
            model_name='plaidpersonalfinancecategories',
            name='general_services',
        ),
        migrations.RemoveField(
            model_name='plaidpersonalfinancecategories',
            name='government_and_non_profit',
        ),
        migrations.RemoveField(
            model_name='plaidpersonalfinancecategories',
            name='income',
        ),
        migrations.RemoveField(
            model_name='plaidpersonalfinancecategories',
            name='loan_payments',
        ),
        migrations.RemoveField(
            model_name='plaidpersonalfinancecategories',
            name='medical',
        ),
        migrations.RemoveField(
            model_name='plaidpersonalfinancecategories',
            name='transfer_in',
        ),
        migrations.RemoveField(
            model_name='plaidpersonalfinancecategories',
            name='transfer_out',
        ),
        migrations.AddField(
            model_name='deposit',
            name='early_access_amount',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='investment',
            name='deposit',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.deposit'),
        ),
        migrations.AddField(
            model_name='plaidcashbacktransaction',
            name='flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plaiditem',
            name='institution_id',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='plaiditem',
            name='institution_name',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='plaiditem',
            name='update_code',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='robinhooddeposit',
            name='early_access_amount',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='userinvestmentgraph',
            name='overdraft_protection',
            field=models.BooleanField(default=True),
        ),
    ]

