# Generated by Django 5.1.3 on 2025-03-22 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_investments_stockdata_userinvestmentgraph_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinvestmentgraph',
            name='cumulative_amount',
        ),
        migrations.RemoveField(
            model_name='userinvestmentgraph',
            name='most_recent_date',
        ),
    ]
