# Generated by Django 5.1.3 on 2025-04-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_investments_buy'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='pre_account_id',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
