# Generated by Django 5.1.3 on 2025-05-08 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_deposit_investment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='early_access_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='robinhooddeposit',
            name='early_access_amount',
            field=models.FloatField(null=True),
        ),
    ]


