# Generated by Django 5.2.1 on 2025-06-19 02:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_plaidlinkwebhook_event_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plaidlinkwebhook',
            name='time_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
