# Generated by Django 5.1.3 on 2025-05-08 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_deposit_early_access_amount_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='investment',
            name='unique_investment',
        ),
        migrations.RemoveField(
            model_name='userinvestmentgraph',
            name='overdraft_protection',
        ),
        migrations.AddField(
            model_name='userbrokerageinfo',
            name='overdraft_protection',
            field=models.BooleanField(default=True),
        ),
    ]
