# Generated by Django 5.1.3 on 2025-03-22 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_userinvestmentgraph_cumulative_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinvestmentgraph',
            name='data',
            field=models.JSONField(default=list),
        ),
    ]
