# Generated by Django 5.2.1 on 2025-06-25 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_plaidlinkwebhook_time_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdata',
            name='BTC',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='BTCUSD',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='robinhoodstockorder',
            name='user_cancel_request_state',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
