# Generated by Django 5.2.1 on 2025-07-08 21:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_stockdata_btc_stockdata_btcusd_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='id',
        ),
        migrations.AddField(
            model_name='investment',
            name='_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='UserInvestmentGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('icon', models.CharField()),
                ('amount', models.FloatField()),
                ('inflation', models.FloatField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
