# Generated by Django 5.1.3 on 2025-03-22 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_userinvestmentgraph_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investments',
            name='cumulative_quantities',
            field=models.JSONField(default=dict),
        ),
    ]
