# Generated by Django 5.1.3 on 2025-01-15 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_userbrokerageinfo_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplaidinfo',
            name='accessToken',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userplaidinfo',
            name='clientUserId',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userplaidinfo',
            name='countryCodes',
            field=models.CharField(choices=[], default=None, max_length=2),
        ),
        migrations.AlterField(
            model_name='userplaidinfo',
            name='itemId',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userplaidinfo',
            name='language',
            field=models.CharField(choices=[], default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='userplaidinfo',
            name='userToken',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
