# Generated by Django 5.1.3 on 2025-05-10 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_investment_unique_investment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robinhooddeposit',
            name='plaid_account_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]

