# Generated by Django 5.1.3 on 2025-05-11 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_robinhooddeposit_plaid_account_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plaidpersonalfinancecategories',
            old_name='entertainment',
            new_name='dining',
        ),
        migrations.RenameField(
            model_name='plaidpersonalfinancecategories',
            old_name='food_and_drink',
            new_name='groceries',
        ),
        migrations.RenameField(
            model_name='plaidpersonalfinancecategories',
            old_name='general_merchandise',
            new_name='utilities',
        ),
        migrations.RemoveField(
            model_name='plaidpersonalfinancecategories',
            name='home_improvement',
        ),
        migrations.RemoveField(
            model_name='plaidpersonalfinancecategories',
            name='personal_care',
        ),
        migrations.RemoveField(
            model_name='plaidpersonalfinancecategories',
            name='rent_and_utilities',
        ),
        migrations.RemoveField(
            model_name='plaidpersonalfinancecategories',
            name='transportation',
        ),
    ]

