# Generated by Django 5.2.1 on 2025-06-20 08:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_plaiditem_previousrefreshsuccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='app_version',
            field=models.CharField(default='pre_build_8'),
        ),
        migrations.AlterField(
            model_name='log',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='loganon',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='waitlistemail',
            name='date_enrolled',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='PlaidLinkWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(null=True)),
                ('event_id', models.UUIDField(null=True)),
                ('link_session_id', models.CharField(null=True)),
                ('link_token', models.CharField()),
                ('request_id', models.CharField(null=True)),
                ('institution_name', models.CharField(null=True)),
                ('view_name', models.CharField(null=True)),
                ('webhook_code', models.CharField()),
                ('exit_status', models.CharField(null=True)),
                ('error_code', models.CharField(null=True)),
                ('error_message', models.CharField(null=True)),
                ('error_type', models.CharField(null=True)),
                ('time_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'link_session_id', 'event_id'], name='api_plaidli_user_id_c5a57a_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'link_session_id', 'event_id'), name='plaidevent')],
            },
        ),
    ]


