# Generated by Django 5.2.1 on 2025-06-20 08:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_user_app_version_alter_log_date_alter_loganon_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdata',
            name='BTC',
            field=models.FloatField(default=None, null=True),
        ),
    ]

