# Generated by Django 5.2.1 on 2025-06-20 08:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_btc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robinhoodstockorder',
            name='pending_cancel_open_agent',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='robinhoodstockorder',
            name='user_cancel_request_state',
            field=models.CharField(max_length=255, null=True),
        ),
    ]


