# Generated by Django 5.2.1 on 2025-06-20 08:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_rh_model_crypto'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdata',
            name='BTCUSD',
            field=models.FloatField(default=None, null=True),
        ),
    ]


