version: 0.2

env:
  variables:
    ENV_NAME: "abprod"
    REGION: "us-west-1"
    IMAGE: "celery"

phases:
  pre_build:
    commands:
      - echo Logging / auth in to Amazon ECR
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - echo ${ACCOUNT_ID} > account_id.txt
      - aws ecr get-login-password --region ${REGION} | docker login --username AWS --password-stdin ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com

  build:
    commands:
      - echo Build started
      - echo Building the celery docker image
      - ACCOUNT_ID=$(cat account_id.txt)
      - docker build -t ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/${ENV_NAME}-${IMAGE}:latest -f build_files/Dockerfile.celery .

  post_build:
    commands:
      - echo build completed
      - echo pushing celery image in to docker ECR...
      - ACCOUNT_ID=$(cat account_id.txt)
      - docker push ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/${ENV_NAME}-${IMAGE}:latest
      - rm account_id.txt
      - echo Writing celery image definition file..