# Generated by Django 5.1.3 on 2025-01-16 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_create_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitlistEmail',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('date_enrolled', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlaidCashbackTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardAccountId', models.CharField(max_length=255)),
                ('transactionId', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('withdrawAccountId', models.CharField(max_length=255)),
                ('hasBalance', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RobinhoodCashbackDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionId', models.CharField(max_length=255)),
                ('depositId', models.CharField(max_length=255)),
                ('depositState', models.CharField(choices=[], max_length=255)),
                ('deposited', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RobinhoodInvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderId', models.CharField(max_length=255)),
                ('orderState', models.CharField(choices=[], max_length=255)),
                ('price', models.FloatField()),
                ('quantity', models.FloatField()),
                ('invested', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserBrokerageInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brokerage', models.CharField(choices=[('RH', 'Robinhood')], max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPlaidInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countryCodes', models.CharField(choices=[], default=None, max_length=2, null=True)),
                ('language', models.CharField(choices=[], default=None, max_length=2, null=True)),
                ('userToken', models.CharField(default=None, max_length=255, null=True)),
                ('accessToken', models.CharField(default=None, max_length=255, null=True)),
                ('clientUserId', models.CharField(default=None, max_length=255, null=True)),
                ('itemId', models.CharField(default=None, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
