"""
Django settings for accumate_backend project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path  
import environ
import os
from datetime import timedelta
import ssl

env = environ.Env()  

BASE_DIR = Path(__file__).resolve().parent.parent  
# Take environment variables from .env file  
environ.Env.read_env(os.path.join(BASE_DIR, ".env"))  

SECRET_KEY = env("SECRET_KEY", default="change_me")  

DEBUG = env("DEBUG", default=False)  

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=["*"])
# DOMAIN = "127.0.0.1:8000"

EMAIL_HOST = "smtp.gmail.com"
EMAIL_HOST_USER = "accumate-verify@accumatewealth.com"
EMAIL_HOST_PASSWORD = "tjeyouapnqagnvso"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"


REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',  # Enable only JSON responses
    ),
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=7),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=30),
    "ROTATE_REFRESH_TOKENS": True,
    # true if you want to test refreshing in front end, false otherwise
    "BLACKLIST_AFTER_ROTATION": True,
    "TOKEN_BLACKLIST_ENABLED": True
}

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_celery_beat',
    
    'rest_framework_simplejwt.token_blacklist',
    'rest_framework_simplejwt',

    'api',
    'rest_framework',
    'corsheaders',
    'django_celery_results',
    'robin_stocks'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware'
]

ROOT_URLCONF = 'accumate_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'accumate_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
db_cred_dict = dict([pair.split(":") for pair in env("DB_CREDENTIALS").replace('"',"").strip("{").strip("}").split(",")])
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': env.str("DB_NAME"),
        'USER': db_cred_dict.get("username"),
        'PASSWORD': db_cred_dict.get("password"),
        'HOST': env.str("DB_HOST"),
        'PORT': env.str("DB_PORT"),
        # 'OPTIONS': {
        #     'sslmode': 'verify-full',  # Enforces server certificate validation
        #     'sslrootcert': env("DB_CAFILE_PATH")  # Path to the server's certificate
        # }
    }
}

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": "redis://" + env("REDIS_URL"),
        # "OPTIONS": {
        #     'ssl_cert_reqs': ssl.CERT_REQUIRED,  # Enforce server certificate validation
        #     'ssl_ca_certs': env("REDIS_CAFILE_PATH")
        # }
    }
}


# SECURE_SSL_REDIRECT = True
# SESSION_COOKIE_SECURE = True
# SECURE_REFERRER_POLICY = "strict-origin"
# SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

LOGGING = {  
    "version": 1,  
    "disable_existing_loggers": False,  
    "handlers": {"console": {"class": "logging.StreamHandler"}},  
    "loggers": {"": {"handlers": ["console"], "level": "DEBUG"}},  
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https ://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = env.str("STATIC_URL", default="/static/")  
STATIC_ROOT = env.str("STATIC_ROOT", default=BASE_DIR / "staticfiles")
WHITENOISE_USE_FINDERS = True
WHITENOISE_AUTOREFRESH = DEBUG

MEDIA_ROOT = env("MEDIA_ROOT", default=BASE_DIR / "media")  
MEDIA_URL = env("MEDIA_PATH", default="/media/")

REDIS_URL = 'redis://' + env("REDIS_URL", default=None)# + '?ssl_cert_reqs=CERT_REQUIRED'
REDIS_CAFILE_PATH = env("REDIS_CAFILE_PATH", default=None)

SQS_LONG_RUNNING_URL = env("SQS_LONG_RUNNING_URL", default=None)
SQS_USER_INTERACTION_URL = env("SQS_USER_INTERACTION_URL", default=None)
SQS_DLQ_URL = env("SQS_DLQ_URL", default=None)
SQS_CONTROL_URL = env("SQS_CONTROL_URL", default=None)

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'api.User'

CORS_ALLOW_ALL_ORIGINS = True
#mb change this eventually
CORS_ALLOWS_CREDENTIALS = True
#? 
DJANGO_CELERY_RESULTS_TASK_ID_MAX_LENGTH = 255

TWILIO_PHONE_NUMBER = env("TWILIO_PHONE_NUMBER", default="")
TWILIO_ACCOUNT_SID = env("TWILIO_ACCOUNT_SID", default="")
TWILIO_AUTH_TOKEN = env("TWILIO_AUTH_TOKEN", default="")

PLAID_CLIENT_ID = env("PLAID_CLIENT_ID", default="")
PLAID_SECRET = env("PLAID_SECRET", default="")
PLAID_HOST = env("PLAID_HOST", default="")

FMP_KEY = env("FMP_KEY", default="")
