# Generated by Django 5.1.3 on 2025-05-15 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_entertainment_plaidpersonalfinancecategories_dining_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plaiditem',
            name='previousRefreshSuccess',
        ),
    ]

